name: Build Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push container image
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.build-image.outputs.tag }}
      short_tag: ${{ steps.build-image.outputs.short_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            argocd:
              - 'argocd/**'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cucxabong
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.changes.outputs.changes != '[]' }}

      - name: ArgoCD
        uses: docker/build-push-action@v3
        with:
          context: argocd
          push: true
          tags: ghcr.io/cucxabong/argocd:v2.4.15
        if: ${{ steps.changes.outputs.argocd == 'true' }}
